import SiteFooter from "@/components/site-footer";
import SiteHeader from "@/components/site-header";
import { supportEmail } from "@/lib/supportEmail";
import { webOrigin } from "@/lib/webOrigin";

export default async function PrivacyPage() {
  const app = webOrigin();
  const email = supportEmail();

  return (
    <div className="sb-bg">
      <a href="#main" className="sb-skip-link">
        Skip to content
      </a>
      <div className="mx-auto max-w-4xl px-6 py-12 sm:py-16">
        <SiteHeader appOrigin={app} />

        <main id="main" className="mt-10 sb-marketing-shell">
          <div className="sb-card p-8 sm:p-10">
            <div className="sb-title text-4xl leading-[1.05] font-extrabold">
              Privacy Policy
            </div>
            <p className="mt-3 text-sm text-[color:var(--sb-muted)]">
              Effective date: February 6, 2026
            </p>

            <div className="mt-7 grid gap-6 text-sm text-[color:var(--sb-muted)] leading-relaxed">
              <section className="grid gap-2">
                <div className="sb-title text-lg font-extrabold text-[color:var(--sb-fg)]">
                  Summary
                </div>
                <div>
                  Starbeam is a private beta product. We collect the minimum
                  information needed to run the app and deliver a daily pulse.
                  Read-only integrations are used to derive summaries and tasks;
                  we do not send emails or write calendar events in v0.
                </div>
              </section>

              <section className="grid gap-2">
                <div className="sb-title text-lg font-extrabold text-[color:var(--sb-fg)]">
                  Information We Collect
                </div>
                <ul className="list-disc pl-5 grid gap-2">
                  <li>
                    Account information (email, name, avatar) from sign-in.
                  </li>
                  <li>
                    Org configuration you provide (goals, announcements,
                    profile).
                  </li>
                  <li>
                    Integration tokens (stored encrypted) and related metadata
                    (scopes, expiry).
                  </li>
                  <li>
                    Derived items (pulse cards, tasks, source references)
                    generated by the system.
                  </li>
                  <li>Basic operational logs for reliability and security.</li>
                </ul>
              </section>

              <section className="grid gap-2">
                <div className="sb-title text-lg font-extrabold text-[color:var(--sb-fg)]">
                  How We Use Information
                </div>
                <ul className="list-disc pl-5 grid gap-2">
                  <li>
                    Provide and improve the product (pulse generation,
                    onboarding, support).
                  </li>
                  <li>
                    Secure the service (abuse prevention, incident response).
                  </li>
                  <li>
                    Communicate about access and critical product updates.
                  </li>
                </ul>
              </section>

              <section className="grid gap-2">
                <div className="sb-title text-lg font-extrabold text-[color:var(--sb-fg)]">
                  Sharing
                </div>
                <div>
                  We don’t sell your personal information. We may share limited
                  data with infrastructure providers used to run the service
                  (hosting, database, email delivery) under contractual
                  protections.
                </div>
              </section>

              <section className="grid gap-2">
                <div className="sb-title text-lg font-extrabold text-[color:var(--sb-fg)]">
                  Security
                </div>
                <div>
                  We store integration tokens encrypted at rest. We take
                  reasonable measures to protect data, but no system is
                  perfectly secure.
                </div>
              </section>

              <section className="grid gap-2">
                <div className="sb-title text-lg font-extrabold text-[color:var(--sb-fg)]">
                  Contact
                </div>
                <div>
                  Questions or requests:{" "}
                  <a
                    href={`mailto:${email}`}
                    className="text-[color:var(--sb-fg)] hover:underline"
                  >
                    {email}
                  </a>
                  .
                </div>
              </section>
            </div>
          </div>
        </main>

        <SiteFooter appOrigin={app} supportEmail={email} />
      </div>
    </div>
  );
}
